/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author mybas
 */
public class MenuP extends javax.swing.JFrame {

    /**
     * Creates new form IntPrincipal
     */
    public MenuP() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/LGC_Icon.png"));
        setIconImage(icon);
        //Color JFrame
        Color Naranjarest=new Color(217,120,26);
        Color Vinorest=new Color(217,120,26);
        Color Grisrest=new Color(142,0,16);
        Color Blancorest=new Color(255,255,255);
        this.getContentPane().setBackground(Naranjarest);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MenuPP = new javax.swing.JButton();
        AdministracionPP = new javax.swing.JButton();
        AdministracionPP1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Le Grand Chevalier");
        setBackground(new java.awt.Color(217, 120, 26));
        setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(960, 600));
        setName("MP"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(960, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Le Grand Chevalier.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(760, 308));
        jLabel1.setMinimumSize(new java.awt.Dimension(760, 308));

        MenuPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/platos normal.png"))); // NOI18N
        MenuPP.setBorder(null);
        MenuPP.setBorderPainted(false);
        MenuPP.setContentAreaFilled(false);
        MenuPP.setMaximumSize(new java.awt.Dimension(242, 70));
        MenuPP.setMinimumSize(new java.awt.Dimension(242, 70));
        MenuPP.setPreferredSize(new java.awt.Dimension(242, 70));
        MenuPP.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/platos presionado.png"))); // NOI18N
        MenuPP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/platos arriba.png"))); // NOI18N
        MenuPP.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/platos arriba.png"))); // NOI18N

        AdministracionPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/bebidas normal.png"))); // NOI18N
        AdministracionPP.setBorder(null);
        AdministracionPP.setBorderPainted(false);
        AdministracionPP.setContentAreaFilled(false);
        AdministracionPP.setMaximumSize(new java.awt.Dimension(242, 70));
        AdministracionPP.setMinimumSize(new java.awt.Dimension(242, 70));
        AdministracionPP.setPreferredSize(new java.awt.Dimension(242, 70));
        AdministracionPP.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/bebidas presionado.png"))); // NOI18N
        AdministracionPP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/bebidas arriba.png"))); // NOI18N
        AdministracionPP.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/bebidas arriba.png"))); // NOI18N

        AdministracionPP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/postres normal.png"))); // NOI18N
        AdministracionPP1.setBorder(null);
        AdministracionPP1.setBorderPainted(false);
        AdministracionPP1.setContentAreaFilled(false);
        AdministracionPP1.setMaximumSize(new java.awt.Dimension(242, 70));
        AdministracionPP1.setMinimumSize(new java.awt.Dimension(242, 70));
        AdministracionPP1.setPreferredSize(new java.awt.Dimension(242, 70));
        AdministracionPP1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/postres presionado.png"))); // NOI18N
        AdministracionPP1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/postres arriba.png"))); // NOI18N
        AdministracionPP1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/postres arriba.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(MenuPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(AdministracionPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(AdministracionPP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdministracionPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdministracionPP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministracionPP;
    private javax.swing.JButton AdministracionPP1;
    private javax.swing.JButton MenuPP;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
