/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author mybas
 */
public class MPlatos extends javax.swing.JFrame {

    /**
     * Creates new form IntPrincipal
     */
    public MPlatos() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/LGC_Icon.png"));
        setIconImage(icon);
        //Color JFrame
        Color Naranjarest = new Color(217, 120, 26);
        Color Vinorest = new Color(142, 0, 16);
        Color Grisrest = new Color(16, 19, 24);
        Color Blancorest = new Color(255, 255, 255);

        this.getContentPane().setBackground(Naranjarest);
        PanelRojo.setBackground(Vinorest);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRojo = new javax.swing.JPanel();
        LabelOrden = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        CocinaAD = new javax.swing.JButton();
        CocinaAD1 = new javax.swing.JButton();
        LabelPlatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Le Grand Chevalier");
        setBackground(new java.awt.Color(217, 120, 26));
        setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(960, 600));
        setName("MP"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(960, 600));

        LabelOrden.setFont(new java.awt.Font("Freestyle Script", 0, 72)); // NOI18N
        LabelOrden.setForeground(new java.awt.Color(255, 255, 255));
        LabelOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelOrden.setText("Orden");

        jList1.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        CocinaAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/enviar normal.png"))); // NOI18N
        CocinaAD.setBorder(null);
        CocinaAD.setBorderPainted(false);
        CocinaAD.setContentAreaFilled(false);
        CocinaAD.setMaximumSize(new java.awt.Dimension(90, 33));
        CocinaAD.setMinimumSize(new java.awt.Dimension(90, 33));
        CocinaAD.setPreferredSize(new java.awt.Dimension(90, 33));
        CocinaAD.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/enviar presionado.png"))); // NOI18N
        CocinaAD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/Enviar arriba.png"))); // NOI18N
        CocinaAD.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/Enviar arriba.png"))); // NOI18N

        CocinaAD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/imprimir normal.png"))); // NOI18N
        CocinaAD1.setBorder(null);
        CocinaAD1.setBorderPainted(false);
        CocinaAD1.setContentAreaFilled(false);
        CocinaAD1.setMaximumSize(new java.awt.Dimension(90, 33));
        CocinaAD1.setMinimumSize(new java.awt.Dimension(90, 33));
        CocinaAD1.setPreferredSize(new java.awt.Dimension(90, 33));
        CocinaAD1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/imprimir presionado.png"))); // NOI18N
        CocinaAD1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/imprimir arriba.png"))); // NOI18N
        CocinaAD1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/imprimir arriba.png"))); // NOI18N

        javax.swing.GroupLayout PanelRojoLayout = new javax.swing.GroupLayout(PanelRojo);
        PanelRojo.setLayout(PanelRojoLayout);
        PanelRojoLayout.setHorizontalGroup(
            PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRojoLayout.createSequentialGroup()
                .addGroup(PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRojoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(LabelOrden))
                    .addGroup(PanelRojoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRojoLayout.createSequentialGroup()
                                .addComponent(CocinaAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CocinaAD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        PanelRojoLayout.setVerticalGroup(
            PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRojoLayout.createSequentialGroup()
                .addComponent(LabelOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CocinaAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CocinaAD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        LabelPlatos.setFont(new java.awt.Font("Freestyle Script", 0, 72)); // NOI18N
        LabelPlatos.setForeground(new java.awt.Color(16, 19, 24));
        LabelPlatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPlatos.setText("Platos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(LabelPlatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(PanelRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelPlatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelRojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MPlatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CocinaAD;
    private javax.swing.JButton CocinaAD1;
    private javax.swing.JLabel LabelOrden;
    private javax.swing.JLabel LabelPlatos;
    private javax.swing.JPanel PanelRojo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
