/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author mybas
 */
public class MPlatos extends javax.swing.JFrame {

    /**
     * Creates new form IntPrincipal
     */
    public MPlatos() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/LGC_Icon.png"));
        setIconImage(icon);
        //Color JFrame
        Color Naranjarest = new Color(217, 120, 26);
        Color Vinorest = new Color(142, 0, 16);
        Color Grisrest = new Color(16, 19, 24);
        Color Blancorest = new Color(255, 255, 255);

        this.getContentPane().setBackground(Naranjarest);
        PanelRojo.setBackground(Vinorest);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRojo = new javax.swing.JPanel();
        LabelOrden = new javax.swing.JLabel();
        LabelPlatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Le Grand Chevalier");
        setBackground(new java.awt.Color(217, 120, 26));
        setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(960, 600));
        setName("MP"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(960, 600));

        LabelOrden.setFont(new java.awt.Font("Freestyle Script", 0, 72)); // NOI18N
        LabelOrden.setForeground(new java.awt.Color(255, 255, 255));
        LabelOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelOrden.setText("Orden");

        javax.swing.GroupLayout PanelRojoLayout = new javax.swing.GroupLayout(PanelRojo);
        PanelRojo.setLayout(PanelRojoLayout);
        PanelRojoLayout.setHorizontalGroup(
            PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRojoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(LabelOrden)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        PanelRojoLayout.setVerticalGroup(
            PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRojoLayout.createSequentialGroup()
                .addComponent(LabelOrden)
                .addGap(0, 0, 0))
        );

        LabelPlatos.setFont(new java.awt.Font("Freestyle Script", 0, 72)); // NOI18N
        LabelPlatos.setForeground(new java.awt.Color(16, 19, 24));
        LabelPlatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPlatos.setText("Platos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(LabelPlatos)
                .addGap(296, 296, 296)
                .addComponent(PanelRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelPlatos)
                .addContainerGap(514, Short.MAX_VALUE))
            .addComponent(PanelRojo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MPlatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelOrden;
    private javax.swing.JLabel LabelPlatos;
    private javax.swing.JPanel PanelRojo;
    // End of variables declaration//GEN-END:variables
}
