/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import modelo.PlatoP;

/**
 *
 * @author mybas
 */
public class MPostres extends javax.swing.JFrame {

    /**
     * Creates new form IntPrincipal
     */
    public MPostres() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/LGC_Icon.png"));
        setIconImage(icon);
        //Color JFrame
        Color Naranjarest = new Color(217, 120, 26);
        Color Vinorest = new Color(142, 0, 16);
        Color Grisrest = new Color(16, 19, 24);
        Color Blancorest = new Color(255, 255, 255);

        this.getContentPane().setBackground(Naranjarest);
        PanelRojo.setBackground(Vinorest);
        DefaultListModel model = new DefaultListModel();
        OrdenPostres.setModel(model);
        if (MPlatos.ptr!=null) {
            mostrarOrden(MPlatos.ptr);
        }
    }

    void mostrarOrden(MPlatos.Orden ptr) {
        DefaultListModel model = (DefaultListModel) OrdenPostres.getModel();
        model.clear();

        MPlatos.Orden p = ptr;
        while (p != null) {
            model.addElement(p.nombre+","+p.cantidad+".");
            p = p.link;
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PanelRojo = new javax.swing.JPanel();
        LabelOrden = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrdenPostres = new javax.swing.JList<>();
        CocinaAD = new javax.swing.JButton();
        CocinaAD1 = new javax.swing.JButton();
        LabelPlatos = new javax.swing.JLabel();
        Scrollp = new javax.swing.JScrollPane();
        Menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        VPostre1 = new javax.swing.JLabel();
        NPostre1 = new javax.swing.JLabel();
        PPostre1 = new javax.swing.JLabel();
        Postre1 = new javax.swing.JCheckBox();
        CPostre1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        VPostre3 = new javax.swing.JLabel();
        NPostre3 = new javax.swing.JLabel();
        PPostre3 = new javax.swing.JLabel();
        Postre3 = new javax.swing.JCheckBox();
        CPostre3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        VPostre2 = new javax.swing.JLabel();
        NPostre2 = new javax.swing.JLabel();
        PPostre2 = new javax.swing.JLabel();
        Postre2 = new javax.swing.JCheckBox();
        CPostre2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        VPostre4 = new javax.swing.JLabel();
        NPostre4 = new javax.swing.JLabel();
        PPostre4 = new javax.swing.JLabel();
        Postre4 = new javax.swing.JCheckBox();
        CPostre4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        VPostre5 = new javax.swing.JLabel();
        NPostre5 = new javax.swing.JLabel();
        PPostre5 = new javax.swing.JLabel();
        Postre5 = new javax.swing.JCheckBox();
        CPostre5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        VPostre6 = new javax.swing.JLabel();
        NPostre6 = new javax.swing.JLabel();
        PPostre6 = new javax.swing.JLabel();
        Postre6 = new javax.swing.JCheckBox();
        CPostre6 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        VPostre7 = new javax.swing.JLabel();
        NPostre7 = new javax.swing.JLabel();
        PPostre7 = new javax.swing.JLabel();
        Postre7 = new javax.swing.JCheckBox();
        CPostre7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Le Grand Chevalier");
        setBackground(new java.awt.Color(217, 120, 26));
        setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(960, 600));
        setName("MP"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(960, 600));

        LabelOrden.setFont(new java.awt.Font("Freestyle Script", 0, 72)); // NOI18N
        LabelOrden.setForeground(new java.awt.Color(255, 255, 255));
        LabelOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelOrden.setText("Orden");

        OrdenPostres.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        OrdenPostres.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(OrdenPostres);

        CocinaAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/enviar normal.png"))); // NOI18N
        CocinaAD.setBorder(null);
        CocinaAD.setBorderPainted(false);
        CocinaAD.setContentAreaFilled(false);
        CocinaAD.setMaximumSize(new java.awt.Dimension(90, 33));
        CocinaAD.setMinimumSize(new java.awt.Dimension(90, 33));
        CocinaAD.setPreferredSize(new java.awt.Dimension(90, 33));
        CocinaAD.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/enviar presionado.png"))); // NOI18N
        CocinaAD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/Enviar arriba.png"))); // NOI18N
        CocinaAD.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/Enviar arriba.png"))); // NOI18N

        CocinaAD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/imprimir normal.png"))); // NOI18N
        CocinaAD1.setBorder(null);
        CocinaAD1.setBorderPainted(false);
        CocinaAD1.setContentAreaFilled(false);
        CocinaAD1.setMaximumSize(new java.awt.Dimension(90, 33));
        CocinaAD1.setMinimumSize(new java.awt.Dimension(90, 33));
        CocinaAD1.setPreferredSize(new java.awt.Dimension(90, 33));
        CocinaAD1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/imprimir presionado.png"))); // NOI18N
        CocinaAD1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/imprimir arriba.png"))); // NOI18N
        CocinaAD1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/imprimir arriba.png"))); // NOI18N

        javax.swing.GroupLayout PanelRojoLayout = new javax.swing.GroupLayout(PanelRojo);
        PanelRojo.setLayout(PanelRojoLayout);
        PanelRojoLayout.setHorizontalGroup(
            PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRojoLayout.createSequentialGroup()
                .addGroup(PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRojoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(LabelOrden))
                    .addGroup(PanelRojoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRojoLayout.createSequentialGroup()
                                .addComponent(CocinaAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CocinaAD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        PanelRojoLayout.setVerticalGroup(
            PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRojoLayout.createSequentialGroup()
                .addComponent(LabelOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CocinaAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CocinaAD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LabelPlatos.setFont(new java.awt.Font("Freestyle Script", 0, 72)); // NOI18N
        LabelPlatos.setForeground(new java.awt.Color(16, 19, 24));
        LabelPlatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPlatos.setText("Postres");

        Scrollp.setBackground(new java.awt.Color(217, 120, 26));
        Scrollp.setBorder(null);
        Scrollp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Menu.setBackground(new java.awt.Color(217, 120, 26));
        Menu.setMaximumSize(new java.awt.Dimension(688, 830));
        Menu.setMinimumSize(new java.awt.Dimension(688, 830));
        Menu.setPreferredSize(new java.awt.Dimension(688, 830));

        jPanel1.setBackground(new java.awt.Color(16, 19, 24));
        jPanel1.setMaximumSize(new java.awt.Dimension(166, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(166, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(166, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setMaximumSize(new java.awt.Dimension(146, 146));
        jPanel13.setMinimumSize(new java.awt.Dimension(146, 146));
        jPanel13.setPreferredSize(new java.awt.Dimension(146, 146));

        VPostre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Carta/Postres/Baba au Rhum.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NPostre1.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        NPostre1.setForeground(new java.awt.Color(255, 255, 255));
        NPostre1.setText("Baba au Rhum");

        PPostre1.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PPostre1.setForeground(new java.awt.Color(255, 255, 255));
        PPostre1.setText("$ 92 300");

        Postre1.setBorder(null);
        Postre1.setContentAreaFilled(false);
        Postre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check normal.png"))); // NOI18N
        Postre1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba s.png"))); // NOI18N
        Postre1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check seleccionado.png"))); // NOI18N
        Postre1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Postre1ItemStateChanged(evt);
            }
        });

        CPostre1.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        CPostre1.setForeground(new java.awt.Color(16, 19, 24));
        CPostre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPostre1.setText("1");
        CPostre1.setBorder(null);
        CPostre1.setMaximumSize(new java.awt.Dimension(20, 20));
        CPostre1.setMinimumSize(new java.awt.Dimension(20, 20));
        CPostre1.setPreferredSize(new java.awt.Dimension(20, 20));
        CPostre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPostre1MouseClicked(evt);
            }
        });
        CPostre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPostre1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NPostre1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PPostre1)
                            .addComponent(Postre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CPostre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPostre1)
                .addGap(6, 6, 6)
                .addComponent(PPostre1)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Postre1)
                    .addComponent(CPostre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(16, 19, 24));
        jPanel2.setMaximumSize(new java.awt.Dimension(166, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(166, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(166, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setMaximumSize(new java.awt.Dimension(146, 146));
        jPanel15.setMinimumSize(new java.awt.Dimension(146, 146));

        VPostre3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Carta/Postres/Crème brûlée.png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NPostre3.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        NPostre3.setForeground(new java.awt.Color(255, 255, 255));
        NPostre3.setText("Crème Brûlée");

        PPostre3.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PPostre3.setForeground(new java.awt.Color(255, 255, 255));
        PPostre3.setText("$ 87 600");

        Postre3.setBorder(null);
        Postre3.setContentAreaFilled(false);
        Postre3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check normal.png"))); // NOI18N
        Postre3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba s.png"))); // NOI18N
        Postre3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check seleccionado.png"))); // NOI18N
        Postre3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Postre3ItemStateChanged(evt);
            }
        });

        CPostre3.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        CPostre3.setForeground(new java.awt.Color(16, 19, 24));
        CPostre3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPostre3.setText("1");
        CPostre3.setBorder(null);
        CPostre3.setMaximumSize(new java.awt.Dimension(20, 20));
        CPostre3.setMinimumSize(new java.awt.Dimension(20, 20));
        CPostre3.setPreferredSize(new java.awt.Dimension(20, 20));
        CPostre3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPostre3MouseClicked(evt);
            }
        });
        CPostre3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPostre3KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NPostre3)
                            .addComponent(PPostre3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Postre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CPostre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPostre3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPostre3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Postre3)
                    .addComponent(CPostre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(16, 19, 24));
        jPanel3.setMaximumSize(new java.awt.Dimension(166, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(166, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(166, 255));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setMaximumSize(new java.awt.Dimension(146, 146));
        jPanel14.setMinimumSize(new java.awt.Dimension(146, 146));

        VPostre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Carta/Postres/Clafoutis.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NPostre2.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        NPostre2.setForeground(new java.awt.Color(255, 255, 255));
        NPostre2.setText("Clafoutis");

        PPostre2.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PPostre2.setForeground(new java.awt.Color(255, 255, 255));
        PPostre2.setText("$ 72 900");

        Postre2.setBorder(null);
        Postre2.setContentAreaFilled(false);
        Postre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check normal.png"))); // NOI18N
        Postre2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba s.png"))); // NOI18N
        Postre2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check seleccionado.png"))); // NOI18N
        Postre2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Postre2ItemStateChanged(evt);
            }
        });

        CPostre2.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        CPostre2.setForeground(new java.awt.Color(16, 19, 24));
        CPostre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPostre2.setText("1");
        CPostre2.setBorder(null);
        CPostre2.setMaximumSize(new java.awt.Dimension(20, 20));
        CPostre2.setMinimumSize(new java.awt.Dimension(20, 20));
        CPostre2.setPreferredSize(new java.awt.Dimension(20, 20));
        CPostre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPostre2MouseClicked(evt);
            }
        });
        CPostre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPostre2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NPostre2)
                            .addComponent(PPostre2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Postre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CPostre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPostre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPostre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Postre2)
                    .addComponent(CPostre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel4.setBackground(new java.awt.Color(16, 19, 24));
        jPanel4.setMaximumSize(new java.awt.Dimension(166, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(166, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(166, 255));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setMaximumSize(new java.awt.Dimension(146, 146));
        jPanel16.setMinimumSize(new java.awt.Dimension(146, 146));
        jPanel16.setPreferredSize(new java.awt.Dimension(146, 146));

        VPostre4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Carta/Postres/Croquant de pamplemousse .png"))); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NPostre4.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        NPostre4.setForeground(new java.awt.Color(255, 255, 255));
        NPostre4.setText("Croquant du Pamplemousse");
        NPostre4.setToolTipText("");

        PPostre4.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PPostre4.setForeground(new java.awt.Color(255, 255, 255));
        PPostre4.setText("$ 109 700");

        Postre4.setBorder(null);
        Postre4.setContentAreaFilled(false);
        Postre4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check normal.png"))); // NOI18N
        Postre4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba s.png"))); // NOI18N
        Postre4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check seleccionado.png"))); // NOI18N
        Postre4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Postre4ItemStateChanged(evt);
            }
        });

        CPostre4.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        CPostre4.setForeground(new java.awt.Color(16, 19, 24));
        CPostre4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPostre4.setText("1");
        CPostre4.setBorder(null);
        CPostre4.setMaximumSize(new java.awt.Dimension(20, 20));
        CPostre4.setMinimumSize(new java.awt.Dimension(20, 20));
        CPostre4.setPreferredSize(new java.awt.Dimension(20, 20));
        CPostre4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPostre4MouseClicked(evt);
            }
        });
        CPostre4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPostre4KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NPostre4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PPostre4)
                            .addComponent(Postre4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CPostre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPostre4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPostre4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Postre4)
                    .addComponent(CPostre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel5.setBackground(new java.awt.Color(16, 19, 24));
        jPanel5.setMaximumSize(new java.awt.Dimension(166, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(166, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(166, 255));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setMaximumSize(new java.awt.Dimension(146, 146));
        jPanel17.setMinimumSize(new java.awt.Dimension(146, 146));
        jPanel17.setPreferredSize(new java.awt.Dimension(146, 146));

        VPostre5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Carta/Postres/Eclair au chocolat.png"))); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NPostre5.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        NPostre5.setForeground(new java.awt.Color(255, 255, 255));
        NPostre5.setText("Eclair au Chocolat");

        PPostre5.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PPostre5.setForeground(new java.awt.Color(255, 255, 255));
        PPostre5.setText("$ 112 800");

        Postre5.setBorder(null);
        Postre5.setContentAreaFilled(false);
        Postre5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check normal.png"))); // NOI18N
        Postre5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba s.png"))); // NOI18N
        Postre5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check seleccionado.png"))); // NOI18N
        Postre5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Postre5ItemStateChanged(evt);
            }
        });

        CPostre5.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        CPostre5.setForeground(new java.awt.Color(16, 19, 24));
        CPostre5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPostre5.setText("1");
        CPostre5.setBorder(null);
        CPostre5.setMaximumSize(new java.awt.Dimension(20, 20));
        CPostre5.setMinimumSize(new java.awt.Dimension(20, 20));
        CPostre5.setPreferredSize(new java.awt.Dimension(20, 20));
        CPostre5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPostre5MouseClicked(evt);
            }
        });
        CPostre5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPostre5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NPostre5)
                            .addComponent(PPostre5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Postre5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CPostre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPostre5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPostre5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Postre5)
                    .addComponent(CPostre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel6.setBackground(new java.awt.Color(16, 19, 24));
        jPanel6.setMaximumSize(new java.awt.Dimension(166, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(166, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(166, 255));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setMaximumSize(new java.awt.Dimension(146, 146));
        jPanel18.setMinimumSize(new java.awt.Dimension(146, 146));
        jPanel18.setPreferredSize(new java.awt.Dimension(146, 146));

        VPostre6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Carta/Postres/Givré laitier.png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NPostre6.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        NPostre6.setForeground(new java.awt.Color(255, 255, 255));
        NPostre6.setText("Givré Laitier");

        PPostre6.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PPostre6.setForeground(new java.awt.Color(255, 255, 255));
        PPostre6.setText("$ 100 300");

        Postre6.setBorder(null);
        Postre6.setContentAreaFilled(false);
        Postre6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check normal.png"))); // NOI18N
        Postre6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba s.png"))); // NOI18N
        Postre6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check seleccionado.png"))); // NOI18N
        Postre6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Postre6ItemStateChanged(evt);
            }
        });

        CPostre6.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        CPostre6.setForeground(new java.awt.Color(16, 19, 24));
        CPostre6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPostre6.setText("1");
        CPostre6.setBorder(null);
        CPostre6.setMaximumSize(new java.awt.Dimension(20, 20));
        CPostre6.setMinimumSize(new java.awt.Dimension(20, 20));
        CPostre6.setPreferredSize(new java.awt.Dimension(20, 20));
        CPostre6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPostre6MouseClicked(evt);
            }
        });
        CPostre6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPostre6KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NPostre6)
                            .addComponent(PPostre6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Postre6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CPostre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPostre6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPostre6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Postre6)
                    .addComponent(CPostre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel7.setBackground(new java.awt.Color(16, 19, 24));
        jPanel7.setMaximumSize(new java.awt.Dimension(166, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(166, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(166, 255));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setMaximumSize(new java.awt.Dimension(146, 146));
        jPanel19.setMinimumSize(new java.awt.Dimension(146, 146));
        jPanel19.setPreferredSize(new java.awt.Dimension(146, 146));

        VPostre7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Carta/Postres/Île flottante.png"))); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VPostre7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NPostre7.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        NPostre7.setForeground(new java.awt.Color(255, 255, 255));
        NPostre7.setText("Île Flottante");

        PPostre7.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PPostre7.setForeground(new java.awt.Color(255, 255, 255));
        PPostre7.setText("$ 81 500");

        Postre7.setBorder(null);
        Postre7.setContentAreaFilled(false);
        Postre7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check normal.png"))); // NOI18N
        Postre7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba.png"))); // NOI18N
        Postre7.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check arriba s.png"))); // NOI18N
        Postre7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/check seleccionado.png"))); // NOI18N
        Postre7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Postre7ItemStateChanged(evt);
            }
        });

        CPostre7.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        CPostre7.setForeground(new java.awt.Color(16, 19, 24));
        CPostre7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPostre7.setText("1");
        CPostre7.setBorder(null);
        CPostre7.setMaximumSize(new java.awt.Dimension(20, 20));
        CPostre7.setMinimumSize(new java.awt.Dimension(20, 20));
        CPostre7.setPreferredSize(new java.awt.Dimension(20, 20));
        CPostre7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPostre7MouseClicked(evt);
            }
        });
        CPostre7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPostre7KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Postre7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CPostre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NPostre7)
                    .addComponent(PPostre7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPostre7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PPostre7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Postre7)
                    .addComponent(CPostre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Scrollp.setViewportView(Menu);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/vMenu normal.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setMaximumSize(new java.awt.Dimension(81, 56));
        jButton1.setMinimumSize(new java.awt.Dimension(81, 56));
        jButton1.setPreferredSize(new java.awt.Dimension(81, 56));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/vMenu presionado.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/vMenu arriba.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/vMenu arriba.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(LabelPlatos))
                    .addComponent(Scrollp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPlatos)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Scrollp, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addComponent(PanelRojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuP elec = new MenuP();
        elec.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Postre1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Postre1ItemStateChanged
        int codigo = 6800;
        if (Postre1.isSelected()) {
            if (CPostre1.getText().isEmpty()) {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), 1);
                CPostre1.setText("1");
            } else {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), Integer.parseInt(CPostre1.getText()));
            }
            mostrarOrden(MPlatos.ptr);
        } else {
            MPlatos.ptr = MPlatos.QuitarPlato(MPlatos.ptr, codigo);
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_Postre1ItemStateChanged

    private void Postre2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Postre2ItemStateChanged
        int codigo = 3400;
        if (Postre2.isSelected()) {
            if (CPostre2.getText().isEmpty()) {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), 1);
                CPostre2.setText("1");
            } else {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), Integer.parseInt(CPostre2.getText()));
            }
            mostrarOrden(MPlatos.ptr);
        } else {
            MPlatos.ptr = MPlatos.QuitarPlato(MPlatos.ptr, codigo);
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_Postre2ItemStateChanged

    private void Postre3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Postre3ItemStateChanged
        int codigo = 5900;
        if (Postre3.isSelected()) {
            if (CPostre3.getText().isEmpty()) {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), 1);
                CPostre3.setText("1");
            } else {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), Integer.parseInt(CPostre3.getText()));
            }
            mostrarOrden(MPlatos.ptr);
        } else {
            MPlatos.ptr = MPlatos.QuitarPlato(MPlatos.ptr, codigo);
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_Postre3ItemStateChanged

    private void Postre4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Postre4ItemStateChanged
        int codigo = 6100;
        if (Postre4.isSelected()) {
            if (CPostre4.getText().isEmpty()) {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), 1);
                CPostre4.setText("1");
            } else {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), Integer.parseInt(CPostre4.getText()));
            }
            mostrarOrden(MPlatos.ptr);
        } else {
            MPlatos.ptr = MPlatos.QuitarPlato(MPlatos.ptr, codigo);
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_Postre4ItemStateChanged

    private void Postre5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Postre5ItemStateChanged
        int codigo = 7200;
        if (Postre5.isSelected()) {
            if (CPostre5.getText().isEmpty()) {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), 1);
                CPostre5.setText("1");
            } else {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), Integer.parseInt(CPostre5.getText()));
            }
            mostrarOrden(MPlatos.ptr);
        } else {
            MPlatos.ptr = MPlatos.QuitarPlato(MPlatos.ptr, codigo);
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_Postre5ItemStateChanged

    private void Postre6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Postre6ItemStateChanged
        int codigo = 1700;
        if (Postre6.isSelected()) {
            if (CPostre6.getText().isEmpty()) {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), 1);
                CPostre6.setText("1");
            } else {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), Integer.parseInt(CPostre6.getText()));
            }
            mostrarOrden(MPlatos.ptr);
        } else {
            MPlatos.ptr = MPlatos.QuitarPlato(MPlatos.ptr, codigo);
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_Postre6ItemStateChanged

    private void Postre7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Postre7ItemStateChanged
        int codigo = 9000;
        if (Postre7.isSelected()) {
            if (CPostre7.getText().isEmpty()) {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), 1);
                CPostre7.setText("1");
            } else {
                MPlatos.ptr = MPlatos.agregarPlato(MPlatos.ptr, codigo, PlatoP.Buscarnombre(codigo), PlatoP.Buscarprecio(codigo), Integer.parseInt(CPostre7.getText()));
            }
            mostrarOrden(MPlatos.ptr);
        } else {
            MPlatos.ptr = MPlatos.QuitarPlato(MPlatos.ptr, codigo);
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_Postre7ItemStateChanged

    private void CPostre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPostre1MouseClicked
        CPostre1.setText("");
    }//GEN-LAST:event_CPostre1MouseClicked

    private void CPostre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPostre1KeyTyped
        char c = evt.getKeyChar();
        evt.consume();
        if (!Character.isDigit(c) || c == '0') {
            CPostre1.setText("1");
        } else {
            CPostre1.setText("");
            CPostre1.setText("" + c);
        }
        if (Postre1.isSelected()) {
            MPlatos.actualizarPlato(MPlatos.ptr, 6800, Integer.parseInt(CPostre1.getText()));
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_CPostre1KeyTyped

    private void CPostre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPostre2MouseClicked
        CPostre2.setText("");
    }//GEN-LAST:event_CPostre2MouseClicked

    private void CPostre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPostre2KeyTyped
        char c = evt.getKeyChar();
        evt.consume();
        if (!Character.isDigit(c) || c == '0') {
            CPostre2.setText("1");
        } else {
            CPostre2.setText("");
            CPostre2.setText("" + c);
        }
        if (Postre2.isSelected()) {
            MPlatos.actualizarPlato(MPlatos.ptr, 3400, Integer.parseInt(CPostre2.getText()));
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_CPostre2KeyTyped

    private void CPostre3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPostre3MouseClicked
        CPostre3.setText("");
    }//GEN-LAST:event_CPostre3MouseClicked

    private void CPostre3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPostre3KeyTyped
        char c = evt.getKeyChar();
        evt.consume();
        if (!Character.isDigit(c) || c == '0') {
            CPostre3.setText("1");
        } else {
            CPostre3.setText("");
            CPostre3.setText("" + c);
        }
        if (Postre3.isSelected()) {
            MPlatos.actualizarPlato(MPlatos.ptr, 5900, Integer.parseInt(CPostre3.getText()));
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_CPostre3KeyTyped

    private void CPostre4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPostre4MouseClicked
        CPostre4.setText("");
    }//GEN-LAST:event_CPostre4MouseClicked

    private void CPostre4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPostre4KeyTyped
        char c = evt.getKeyChar();
        evt.consume();
        if (!Character.isDigit(c) || c == '0') {
            CPostre4.setText("1");
        } else {
            CPostre4.setText("");
            CPostre4.setText("" + c);
        }
        if (Postre4.isSelected()) {
            MPlatos.actualizarPlato(MPlatos.ptr, 6100, Integer.parseInt(CPostre4.getText()));
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_CPostre4KeyTyped

    private void CPostre5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPostre5MouseClicked
        CPostre5.setText("");
    }//GEN-LAST:event_CPostre5MouseClicked

    private void CPostre5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPostre5KeyTyped
        char c = evt.getKeyChar();
        evt.consume();
        if (!Character.isDigit(c) || c == '0') {
            CPostre5.setText("1");
        } else {
            CPostre5.setText("");
            CPostre5.setText("" + c);
        }
        if (Postre5.isSelected()) {
            MPlatos.actualizarPlato(MPlatos.ptr, 7200, Integer.parseInt(CPostre5.getText()));
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_CPostre5KeyTyped

    private void CPostre6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPostre6MouseClicked
        CPostre6.setText("");
    }//GEN-LAST:event_CPostre6MouseClicked

    private void CPostre6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPostre6KeyTyped
        char c = evt.getKeyChar();
        evt.consume();
        if (!Character.isDigit(c) || c == '0') {
            CPostre6.setText("1");
        } else {
            CPostre6.setText("");
            CPostre6.setText("" + c);
        }
        if (Postre6.isSelected()) {
            MPlatos.actualizarPlato(MPlatos.ptr, 1700, Integer.parseInt(CPostre6.getText()));
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_CPostre6KeyTyped

    private void CPostre7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPostre7MouseClicked
        CPostre7.setText("");
    }//GEN-LAST:event_CPostre7MouseClicked

    private void CPostre7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPostre7KeyTyped
        char c = evt.getKeyChar();
        evt.consume();
        if (!Character.isDigit(c) || c == '0') {
            CPostre7.setText("1");
        } else {
            CPostre7.setText("");
            CPostre7.setText("" + c);
        }
        if (Postre7.isSelected()) {
            MPlatos.actualizarPlato(MPlatos.ptr, 9000, Integer.parseInt(CPostre7.getText()));
            mostrarOrden(MPlatos.ptr);
        }
    }//GEN-LAST:event_CPostre7KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MPostres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MPostres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPostre1;
    private javax.swing.JTextField CPostre2;
    private javax.swing.JTextField CPostre3;
    private javax.swing.JTextField CPostre4;
    private javax.swing.JTextField CPostre5;
    private javax.swing.JTextField CPostre6;
    private javax.swing.JTextField CPostre7;
    private javax.swing.JButton CocinaAD;
    private javax.swing.JButton CocinaAD1;
    private javax.swing.JLabel LabelOrden;
    private javax.swing.JLabel LabelPlatos;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel NPostre1;
    private javax.swing.JLabel NPostre2;
    private javax.swing.JLabel NPostre3;
    private javax.swing.JLabel NPostre4;
    private javax.swing.JLabel NPostre5;
    private javax.swing.JLabel NPostre6;
    private javax.swing.JLabel NPostre7;
    private javax.swing.JList<String> OrdenPostres;
    private javax.swing.JLabel PPostre1;
    private javax.swing.JLabel PPostre2;
    private javax.swing.JLabel PPostre3;
    private javax.swing.JLabel PPostre4;
    private javax.swing.JLabel PPostre5;
    private javax.swing.JLabel PPostre6;
    private javax.swing.JLabel PPostre7;
    private javax.swing.JPanel PanelRojo;
    private javax.swing.JCheckBox Postre1;
    private javax.swing.JCheckBox Postre2;
    private javax.swing.JCheckBox Postre3;
    private javax.swing.JCheckBox Postre4;
    private javax.swing.JCheckBox Postre5;
    private javax.swing.JCheckBox Postre6;
    private javax.swing.JCheckBox Postre7;
    private javax.swing.JScrollPane Scrollp;
    private javax.swing.JLabel VPostre1;
    private javax.swing.JLabel VPostre2;
    private javax.swing.JLabel VPostre3;
    private javax.swing.JLabel VPostre4;
    private javax.swing.JLabel VPostre5;
    private javax.swing.JLabel VPostre6;
    private javax.swing.JLabel VPostre7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
