/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author mybas
 */
public class SesionMenu extends javax.swing.JFrame {

    String clave;
    String puntos;
    int cont;

    /**
     * Creates new form Sesion
     */
    public SesionMenu() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/LGC_Icon.png"));
        setIconImage(icon);
        Color mostazarest = new Color(213, 170, 65);
        this.getContentPane().setBackground(mostazarest);
        clave = "";
        puntos = "";
        cont = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idMes = new javax.swing.JTextField();
        PassMes = new javax.swing.JTextField();
        ISMes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setBackground(new java.awt.Color(213, 170, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LSM.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel2.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Identificación:");

        jLabel3.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jLabel3.setText("Contraseña:");
        jLabel3.setMaximumSize(new java.awt.Dimension(85, 29));
        jLabel3.setMinimumSize(new java.awt.Dimension(85, 29));
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 29));

        idMes.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        idMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idMes.setBorder(null);
        idMes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        idMes.setMaximumSize(new java.awt.Dimension(200, 30));
        idMes.setMinimumSize(new java.awt.Dimension(200, 30));
        idMes.setPreferredSize(new java.awt.Dimension(200, 30));
        idMes.setRequestFocusEnabled(false);
        idMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idMesKeyTyped(evt);
            }
        });

        PassMes.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PassMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PassMes.setBorder(null);
        PassMes.setEnabled(false);
        PassMes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        PassMes.setMaximumSize(new java.awt.Dimension(200, 30));
        PassMes.setMinimumSize(new java.awt.Dimension(200, 30));
        PassMes.setPreferredSize(new java.awt.Dimension(200, 30));
        PassMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassMesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PassMesKeyTyped(evt);
            }
        });

        ISMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/ISnormal.png"))); // NOI18N
        ISMes.setBorder(null);
        ISMes.setBorderPainted(false);
        ISMes.setContentAreaFilled(false);
        ISMes.setEnabled(false);
        ISMes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ISMes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ISMes.setMaximumSize(new java.awt.Dimension(85, 26));
        ISMes.setMinimumSize(new java.awt.Dimension(85, 26));
        ISMes.setPreferredSize(new java.awt.Dimension(85, 26));
        ISMes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/ISpresionado.png"))); // NOI18N
        ISMes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/ISarriba.png"))); // NOI18N
        ISMes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesMenu/ISarriba.png"))); // NOI18N
        ISMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ISMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ISMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassMesKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) && cont <= 4) {
            cont++;
            clave = clave + Character.toString(c);
            puntos = puntos + "•";
            PassMes.setText(puntos);
        }
        if (cont > 4) {
            ISMes.setEnabled(true);
        } else {
            ISMes.setEnabled(false);
        }
        evt.consume();
    }//GEN-LAST:event_PassMesKeyTyped

    private void PassMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassMesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE && cont > 1) {
            cont--;
            clave = clave.substring(0, cont - 1);
            puntos = puntos.substring(0, cont - 1);
            PassMes.setText(puntos);
        }
        evt.consume();
    }//GEN-LAST:event_PassMesKeyPressed

    private void idMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idMesKeyTyped
        char c = evt.getKeyChar();
        int tam = idMes.getText().length();
        if (!Character.isDigit(c) || tam > 7) {
            evt.consume();
        }
        if (tam > 6) {
            PassMes.setEnabled(true);
        }
    }//GEN-LAST:event_idMesKeyTyped

    private void ISMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISMesActionPerformed
        MenuP elec = new MenuP();
        elec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ISMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SesionMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ISMes;
    private javax.swing.JTextField PassMes;
    private javax.swing.JTextField idMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
