/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author mybas
 */
public class SesionAdmin extends javax.swing.JFrame {

    String clave;
    String puntos;
    int cont;

    /**
     * Creates new form Sesion
     */
    public SesionAdmin() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/LGC_Icon.png"));
        setIconImage(icon);
        Color Vinorest = new Color(142, 0, 16);
        this.getContentPane().setBackground(Vinorest);
        clave = "";
        puntos = "";
        cont = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idAdmin = new javax.swing.JTextField();
        PassAdmin = new javax.swing.JTextField();
        ISAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setBackground(new java.awt.Color(213, 170, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LSA.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 19, 24));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Identificación:");

        jLabel3.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 19, 24));
        jLabel3.setText("Contraseña:");
        jLabel3.setMaximumSize(new java.awt.Dimension(85, 29));
        jLabel3.setMinimumSize(new java.awt.Dimension(85, 29));
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 29));

        idAdmin.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        idAdmin.setForeground(new java.awt.Color(16, 19, 24));
        idAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idAdmin.setBorder(null);
        idAdmin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        idAdmin.setMaximumSize(new java.awt.Dimension(200, 30));
        idAdmin.setMinimumSize(new java.awt.Dimension(200, 30));
        idAdmin.setPreferredSize(new java.awt.Dimension(200, 30));
        idAdmin.setRequestFocusEnabled(false);
        idAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idAdminKeyTyped(evt);
            }
        });

        PassAdmin.setFont(new java.awt.Font("Freestyle Script", 0, 18)); // NOI18N
        PassAdmin.setForeground(new java.awt.Color(16, 19, 24));
        PassAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PassAdmin.setBorder(null);
        PassAdmin.setEnabled(false);
        PassAdmin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        PassAdmin.setMaximumSize(new java.awt.Dimension(200, 30));
        PassAdmin.setMinimumSize(new java.awt.Dimension(200, 30));
        PassAdmin.setPreferredSize(new java.awt.Dimension(200, 30));
        PassAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassAdminKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PassAdminKeyTyped(evt);
            }
        });

        ISAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesAdmin/ISnormal.png"))); // NOI18N
        ISAdmin.setBorder(null);
        ISAdmin.setBorderPainted(false);
        ISAdmin.setContentAreaFilled(false);
        ISAdmin.setEnabled(false);
        ISAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ISAdmin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ISAdmin.setMaximumSize(new java.awt.Dimension(85, 26));
        ISAdmin.setMinimumSize(new java.awt.Dimension(85, 26));
        ISAdmin.setPreferredSize(new java.awt.Dimension(85, 26));
        ISAdmin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesAdmin/ISpresionado.png"))); // NOI18N
        ISAdmin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesAdmin/ISarriba.png"))); // NOI18N
        ISAdmin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonesAdmin/ISarriba.png"))); // NOI18N
        ISAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ISAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ISAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idAdminKeyTyped
        char c = evt.getKeyChar();
        int tam = idAdmin.getText().length();
        if (!Character.isDigit(c) || tam > 7) {
            evt.consume();
        }
        if (tam > 6) {
            PassAdmin.setEnabled(true);
        }
    }//GEN-LAST:event_idAdminKeyTyped

    private void PassAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassAdminKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE && cont > 1) {
            cont--;
            clave = clave.substring(0, cont - 1);
            puntos = puntos.substring(0, cont - 1);
            PassAdmin.setText(puntos);
            evt.consume();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && cont > 4) {
            AdminP elec = new AdminP();
            elec.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_PassAdminKeyPressed

    private void PassAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassAdminKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) && cont <= 4) {
            cont++;
            clave = clave + Character.toString(c);
            puntos = puntos + "•";
            PassAdmin.setText(puntos);
        }
        if (cont > 4) {
            ISAdmin.setEnabled(true);
        } else {
            ISAdmin.setEnabled(false);
        }
        evt.consume();
    }//GEN-LAST:event_PassAdminKeyTyped

    private void ISAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISAdminActionPerformed
        AdminP elec = new AdminP();
        elec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ISAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SesionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SesionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SesionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SesionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SesionAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ISAdmin;
    private javax.swing.JTextField PassAdmin;
    private javax.swing.JTextField idAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
